# Generated by Django 5.2.3 on 2025-07-01 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['name', '-imdb_rating'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='rating',
            new_name='imdb_rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='users_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.CreateModel(
            name='UserRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Rating',
                'verbose_name_plural': 'User Ratings',
                'ordering': ['user'],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
