# Generated by Django 5.2.3 on 2025-06-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='1', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
