# Generated by Django 5.2.3 on 2025-07-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_movie_options_rename_rating_movie_imdb_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='users_rating',
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
