# Generated by Django 5.2.3 on 2025-07-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_movie_users_rating_alter_movie_imdb_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userratings',
            name='review',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
